// show-sort.cjs — 排序菜单/applySort/列表缩略图 CSS
const fs = require('fs')
const t = fs.readFileSync('src/renderer/src/components/Toolbar.vue', 'utf8')
const i = t.indexOf('openSortMenu')
console.log('=== Toolbar 排序 ===')
console.log(t.slice(Math.max(0, i - 150), i + 1000))
const p = fs.readFileSync('src/renderer/src/util/pipeline.ts', 'utf8')
const j = p.indexOf('export function applySort')
console.log('=== pipeline applySort ===')
console.log(p.slice(j, j + 800))
const g = fs.readFileSync('src/renderer/src/components/AssetGrid.vue', 'utf8')
const k = g.indexOf('.thumb-cell')
console.log('=== AssetGrid thumb-cell ===')
console.log(g.slice(k, k + 500))
